/**
 * PowerSync-Schema-VORLAGE (Teil B): Tabellen/Spalten für die lokale SQLite-Replik.
 * Bewusst SDK-frei (Pakete folgen mit Instanz) — wird in Phase 09b in `new Schema([...])`
 * aus @powersync/react-native übersetzt. Quelle: docs/data-model.md + sync-rules.yaml.
 */
export const SYNCED_TABLES = {
  tasks: [
    'id',
    'workspace_id',
    'project_id',
    'parent_task_id',
    'area_id',
    'title',
    'description',
    'priority',
    'energy',
    'tags',
    'scheduled_for',
    'deadline',
    'estimated_minutes',
    'is_obt',
    'status',
    'completed_at',
    'completed_by',
    'recurrence',
    'position',
    'created_by',
    'created_at',
    'updated_at',
  ],
  habits: [
    'id',
    'workspace_id',
    'area_id',
    'icon',
    'title',
    'identity_statement',
    'frequency_type',
    'frequency_config',
    'reminder_time',
    'current_streak',
    'longest_streak',
    'shield_used_at',
    'archived_at',
    'created_by',
    'created_at',
    'updated_at',
  ],
  habit_logs: ['id', 'habit_id', 'workspace_id', 'user_id', 'logged_for', 'logged_at', 'note'],
  areas: ['id', 'workspace_id', 'name', 'color', 'icon', 'position', 'created_at', 'updated_at'],
  goals: [
    'id',
    'workspace_id',
    'vision_id',
    'area_id',
    'title',
    'why_statement',
    'conviction_score',
    'quarter',
    'deadline',
    'status',
    'progress_pct',
    'archived_at',
    'created_by',
    'created_at',
    'updated_at',
  ],
  projects: [
    'id',
    'workspace_id',
    'goal_id',
    'area_id',
    'title',
    'description',
    'status',
    'is_legacy',
    'deadline',
    'progress_pct',
    'created_by',
    'created_at',
    'updated_at',
  ],
  journal_entries: [
    'id',
    'workspace_id',
    'user_id',
    'entry_date',
    'daily_wins',
    'long_form',
    'mood',
    'tags',
    'created_at',
    'updated_at',
  ],
  // … weitere Tabellen analog beim Feature-Ausbau (Phasen 14+)
} as const;
